// Generated by Framer (ce6e1ae)
import {
    addPropertyControls as e,
    ControlType as r,
    QueryCache as l,
    QueryEngine as t
} from "framer";
import {
    DatabaseCollection as m,
    DatabaseDictionaryIndex as a
} from "./Gk_rXsiQS-0.js";
import {
    resolveRichText as i
} from "./Gk_rXsiQS-1.js";
import {
    resolveRichTextCz as o
} from "./Gk_rXsiQS-3.js";
let c = {
        b73WSs0_n: {
            isNullable: !0,
            type: r.String
        },
        DVPfz2jzc: {
            isNullable: !0,
            type: r.RichText
        },
        HAkmBGjlu: {
            isNullable: !0,
            type: r.ResponsiveImage
        },
        id: {
            isNullable: !1,
            type: r.String
        },
        MUgju5Ygu: {
            isNullable: !0,
            type: r.String
        },
        nextItemId: {
            isNullable: !0,
            type: r.String
        },
        previousItemId: {
            isNullable: !0,
            type: r.String
        },
        q6wyKlkO2: {
            isNullable: !0,
            type: r.String
        },
        vnHoSaeaE: {
            isNullable: !0,
            type: r.ResponsiveImage
        },
        YVDB5NOAE: {
            isNullable: !0,
            type: r.Date
        }
    },
    n = ["id", "DVPfz2jzc"],
    s = {
        type: 1
    },
    f = ["previousItemId", "DVPfz2jzc"],
    u = ["nextItemId", "DVPfz2jzc"],
    d = ["id", "q6wyKlkO2"],
    p = ["q6wyKlkO2", "id"],
    h = ["MUgju5Ygu", "DVPfz2jzc"],
    S = {
        type: 0
    },
    w = ["q6wyKlkO2", "DVPfz2jzc"],
    g = ["YVDB5NOAE", "DVPfz2jzc"],
    y = ["HAkmBGjlu", "DVPfz2jzc"],
    k = ["vnHoSaeaE", "DVPfz2jzc"],
    U = ["b73WSs0_n", "DVPfz2jzc"],
    x = ["DVPfz2jzc", "DVPfz2jzc"],
    N = [],
    R = e => {
        let r = N[e];
        if (r) return r().then(e => e.default);
    },
    G = new t,
    _ = new l(G),
    L = {
        collectionByLocaleId: {
            default: new m({
                chunks: [new URL("./Gk_rXsiQS-chunk-default-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                indexes: [new a({
                    collation: s,
                    collectionSchema: c,
                    fieldNames: n,
                    range: {
                        from: 0,
                        to: 188
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: c,
                    fieldNames: f,
                    range: {
                        from: 188,
                        to: 375
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: c,
                    fieldNames: u,
                    range: {
                        from: 375,
                        to: 558
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: c,
                    fieldNames: d,
                    range: {
                        from: 558,
                        to: 982
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: c,
                    fieldNames: p,
                    range: {
                        from: 982,
                        to: 1406
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: h,
                    range: {
                        from: 1406,
                        to: 1797
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: w,
                    range: {
                        from: 1797,
                        to: 2188
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: g,
                    range: {
                        from: 2188,
                        to: 2358
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: y,
                    range: {
                        from: 2358,
                        to: 4480
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: k,
                    range: {
                        from: 4480,
                        to: 6603
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: U,
                    range: {
                        from: 6603,
                        to: 7259
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: x,
                    range: {
                        from: 7259,
                        to: 7414
                    },
                    url: new URL("./Gk_rXsiQS-indexes-default-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                })],
                resolveRichText: i,
                resolveVectorSetItem: R,
                schema: c
            }),
            Ft06JUrhM: new m({
                chunks: [new URL("./Gk_rXsiQS-chunk-Ft06JUrhM-0.framercms",
                    import.meta.url).href.replace("/modules/", "/cms/")],
                indexes: [new a({
                    collation: s,
                    collectionSchema: c,
                    fieldNames: n,
                    range: {
                        from: 0,
                        to: 188
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: c,
                    fieldNames: f,
                    range: {
                        from: 188,
                        to: 375
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: c,
                    fieldNames: u,
                    range: {
                        from: 375,
                        to: 558
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: c,
                    fieldNames: d,
                    range: {
                        from: 558,
                        to: 982
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: s,
                    collectionSchema: c,
                    fieldNames: p,
                    range: {
                        from: 982,
                        to: 1406
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: h,
                    range: {
                        from: 1406,
                        to: 1803
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: w,
                    range: {
                        from: 1803,
                        to: 2194
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: g,
                    range: {
                        from: 2194,
                        to: 2364
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: y,
                    range: {
                        from: 2364,
                        to: 4486
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: k,
                    range: {
                        from: 4486,
                        to: 6609
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: U,
                    range: {
                        from: 6609,
                        to: 7300
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                }), new a({
                    collation: S,
                    collectionSchema: c,
                    fieldNames: x,
                    range: {
                        from: 7300,
                        to: 7455
                    },
                    url: new URL("./Gk_rXsiQS-indexes-Ft06JUrhM-0.framercms",
                        import.meta.url).href.replace("/modules/", "/cms/")
                })],
                resolveRichText: o,
                resolveVectorSetItem: R,
                schema: c
            })
        },
        displayName: "Blog"
    };
export default L;
e(L, {
    MUgju5Ygu: {
        defaultValue: "",
        title: "Title",
        type: r.String
    },
    q6wyKlkO2: {
        title: "Slug",
        type: r.String
    },
    YVDB5NOAE: {
        title: "Date",
        type: r.Date
    },
    HAkmBGjlu: {
        title: "Preview Image",
        type: r.ResponsiveImage
    },
    vnHoSaeaE: {
        title: "Main Image",
        type: r.ResponsiveImage
    },
    b73WSs0_n: {
        defaultValue: "",
        displayTextArea: !0,
        title: "Excerpt",
        type: r.String
    },
    DVPfz2jzc: {
        defaultValue: "",
        title: "Content",
        type: r.RichText
    },
    previousItemId: {
        dataIdentifier: "local-module:collection/Gk_rXsiQS:default",
        title: "Previous",
        type: r.CollectionReference
    },
    nextItemId: {
        dataIdentifier: "local-module:collection/Gk_rXsiQS:default",
        title: "Next",
        type: r.CollectionReference
    }
});
export const enumToDisplayNameFunctions = {};
export const utils = {
    async getSlugByRecordId(e, r) {
        let [l] = await _.get({
            from: {
                data: L,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "q6wyKlkO2",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "id",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, r).readAsync();
        return l ? .q6wyKlkO2;
    },
    async getRecordIdBySlug(e, r) {
        let [l] = await _.get({
            from: {
                data: L,
                type: "Collection"
            },
            limit: {
                type: "LiteralValue",
                value: 1
            },
            select: [{
                name: "id",
                type: "Identifier"
            }],
            where: {
                left: {
                    name: "q6wyKlkO2",
                    type: "Identifier"
                },
                operator: "==",
                right: {
                    type: "LiteralValue",
                    value: e
                },
                type: "BinaryOperation"
            }
        }, r).readAsync();
        return l ? .id;
    }
};
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "data",
            "name": "data",
            "annotations": {
                "framerSlug": "q6wyKlkO2",
                "framerEnumToDisplayNameUtils": "2",
                "framerCollectionId": "Gk_rXsiQS",
                "framerRecordIdKey": "id",
                "framerData": "",
                "framerContractVersion": "1",
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "false",
                "framerCollectionUtils": "1"
            }
        },
        "utils": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "enumToDisplayNameFunctions": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}