// Generated by Framer (cf240c2)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    Link,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
const enabledGestures = {
    AzhqezM_b: {
        hover: true
    },
    MblpBuNJI: {
        hover: true
    },
    Sj4YIbMBa: {
        hover: true
    }
};
const cycleOrder = ["Sj4YIbMBa", "AzhqezM_b", "MblpBuNJI"];
const serializationHash = "framer-ic0ZY";
const variantClassNames = {
    AzhqezM_b: "framer-v-makjb1",
    MblpBuNJI: "framer-v-e705y3",
    Sj4YIbMBa: "framer-v-1twnrr8"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants === null || variants === void 0 ? void 0 : variants.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value !== null && value !== void 0 ? value : config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Default: "Sj4YIbMBa",
    Muted: "AzhqezM_b",
    Primary: "MblpBuNJI"
};
const getProps = ({
    height,
    id,
    link,
    newTab,
    title,
    width,
    ...props
}) => {
    var _ref, _humanReadableVariantMap_props_variant, _ref1;
    return { ...props,
        amWyVdppW: newTab !== null && newTab !== void 0 ? newTab : props.amWyVdppW,
        ApxukoHYo: (_ref = title !== null && title !== void 0 ? title : props.ApxukoHYo) !== null && _ref !== void 0 ? _ref : "Button",
        QkE8o0HIe: link !== null && link !== void 0 ? link : props.QkE8o0HIe,
        variant: (_ref1 = (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null && _humanReadableVariantMap_props_variant !== void 0 ? _humanReadableVariantMap_props_variant : props.variant) !== null && _ref1 !== void 0 ? _ref1 : "Sj4YIbMBa"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        ApxukoHYo,
        QkE8o0HIe,
        amWyVdppW,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "Sj4YIbMBa",
        enabledGestures,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const ref1 = React.useRef(null);
    const defaultLayoutId = React.useId();
    const sharedStyleClassNames = [];
    const componentViewport = useComponentViewport();
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: QkE8o0HIe,
                    openInNewTab: amWyVdppW,
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(serializationHash,...sharedStyleClassNames,"framer-1twnrr8",className,classNames)} framer-w44gnw`,
                        "data-border": true,
                        "data-framer-name": "Default",
                        layoutDependency: layoutDependency,
                        layoutId: "Sj4YIbMBa",
                        ref: ref !== null && ref !== void 0 ? ref : ref1,
                        style: {
                            "--border-bottom-width": "1px",
                            "--border-color": "var(--token-68c05b50-ca7b-4173-82aa-ed42aea1a9b4, rgba(218, 197, 167, 0.15))",
                            "--border-left-width": "1px",
                            "--border-right-width": "1px",
                            "--border-style": "solid",
                            "--border-top-width": "1px",
                            backgroundColor: "rgba(0, 0, 0, 0)",
                            borderBottomLeftRadius: 8,
                            borderBottomRightRadius: 8,
                            borderTopLeftRadius: 8,
                            borderTopRightRadius: 8,
                            ...style
                        },
                        variants: {
                            "AzhqezM_b-hover": {
                                "--border-color": "var(--token-52eaa3b2-9b53-4c12-9790-fce4171dff3e, rgb(78, 76, 71))",
                                backgroundColor: "var(--token-c18e5c55-e670-494b-9afe-b018358f3867, rgb(17, 17, 17))"
                            },
                            "MblpBuNJI-hover": {
                                "--border-bottom-width": "0px",
                                "--border-left-width": "0px",
                                "--border-right-width": "0px",
                                "--border-top-width": "0px",
                                backgroundColor: "var(--token-ba35ffdc-68bb-41bc-880c-4aa29d4488ec, rgb(20, 20, 19))"
                            },
                            "Sj4YIbMBa-hover": {
                                "--border-color": "var(--token-52eaa3b2-9b53-4c12-9790-fce4171dff3e, rgb(78, 76, 71))"
                            },
                            AzhqezM_b: {
                                "--border-color": "var(--token-68c05b50-ca7b-4173-82aa-ed42aea1a9b4, rgba(239, 231, 210, 0.15))",
                                backgroundColor: "var(--token-cd2934a7-4e35-4347-a32c-9650fca4db23, rgb(242, 242, 242))"
                            },
                            MblpBuNJI: {
                                "--border-bottom-width": "0px",
                                "--border-left-width": "0px",
                                "--border-right-width": "0px",
                                "--border-top-width": "0px",
                                backgroundColor: "var(--token-dca875b7-f855-43c1-bf73-97596e452266, rgb(203, 251, 69))"
                            }
                        },
                        ...addPropertyOverrides({
                            "AzhqezM_b-hover": {
                                "data-framer-name": undefined
                            },
                            "MblpBuNJI-hover": {
                                "data-framer-name": undefined
                            },
                            "Sj4YIbMBa-hover": {
                                "data-framer-name": undefined
                            },
                            AzhqezM_b: {
                                "data-framer-name": "Muted"
                            },
                            MblpBuNJI: {
                                "data-framer-name": "Primary"
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
                                        "--framer-font-family": '"Satoshi", "Satoshi Placeholder", sans-serif',
                                        "--framer-font-size": "12px",
                                        "--framer-letter-spacing": "1px",
                                        "--framer-line-height": "110%",
                                        "--framer-text-alignment": "left",
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, rgb(218, 197, 167)))",
                                        "--framer-text-transform": "uppercase"
                                    },
                                    children: "Button"
                                })
                            }),
                            className: "framer-189euxk",
                            "data-framer-name": "Button",
                            fonts: ["FS;Satoshi-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "EtsprDx5u",
                            style: {
                                "--extracted-r6o4lv": "var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, rgb(218, 197, 167))"
                            },
                            text: ApxukoHYo,
                            variants: {
                                MblpBuNJI: {
                                    "--extracted-r6o4lv": "var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255))"
                                }
                            },
                            verticalAlignment: "top",
                            withExternalLayout: true,
                            ...addPropertyOverrides({
                                MblpBuNJI: {
                                    children: /*#__PURE__*/ _jsx(React.Fragment, {
                                        children: /*#__PURE__*/ _jsx(motion.p, {
                                            style: {
                                                "--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
                                                "--framer-font-family": '"Satoshi", "Satoshi Placeholder", sans-serif',
                                                "--framer-font-size": "12px",
                                                "--framer-letter-spacing": "1px",
                                                "--framer-line-height": "110%",
                                                "--framer-text-alignment": "left",
                                                "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c5446a54-80de-4f79-b24b-55997bf1fe5e, rgb(255, 255, 255)))",
                                                "--framer-text-transform": "uppercase"
                                            },
                                            children: "Button"
                                        })
                                    })
                                }
                            }, baseVariant, gestureVariant)
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-ic0ZY.framer-w44gnw, .framer-ic0ZY .framer-w44gnw { display: block; }", ".framer-ic0ZY.framer-1twnrr8 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 14px 16px 14px 16px; position: relative; text-decoration: none; width: min-content; }", ".framer-ic0ZY .framer-189euxk { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ic0ZY.framer-1twnrr8 { gap: 0px; } .framer-ic0ZY.framer-1twnrr8 > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-ic0ZY.framer-1twnrr8 > :first-child { margin-left: 0px; } .framer-ic0ZY.framer-1twnrr8 > :last-child { margin-right: 0px; } }", '.framer-ic0ZY[data-border="true"]::after, .framer-ic0ZY [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 41
 * @framerIntrinsicWidth 84.5
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"AzhqezM_b":{"layout":["auto","auto"]},"MblpBuNJI":{"layout":["auto","auto"]},"Eq0ThAfha":{"layout":["auto","auto"]},"iKpejFiKn":{"layout":["auto","auto"]},"nvAn5gJ7R":{"layout":["auto","auto"]}}}
 * @framerVariables {"ApxukoHYo":"title","QkE8o0HIe":"link","amWyVdppW":"newTab"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramernEDMPIJV1 = withCSS(Component, css, "framer-ic0ZY");
export default FramernEDMPIJV1;
FramernEDMPIJV1.displayName = "Components/Button";
FramernEDMPIJV1.defaultProps = {
    height: 41,
    width: 84.5
};
addPropertyControls(FramernEDMPIJV1, {
    variant: {
        options: ["Sj4YIbMBa", "AzhqezM_b", "MblpBuNJI"],
        optionTitles: ["Default", "Muted", "Primary"],
        title: "Variant",
        type: ControlType.Enum
    },
    ApxukoHYo: {
        defaultValue: "Button",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    },
    QkE8o0HIe: {
        title: "Link",
        type: ControlType.Link
    },
    amWyVdppW: {
        defaultValue: false,
        title: "New Tab",
        type: ControlType.Boolean
    }
});
addFonts(FramernEDMPIJV1, [{
    explicitInter: true,
    fonts: [{
        family: "Satoshi",
        source: "fontshare",
        style: "normal",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TTX2Z3BF3P6Y5BQT3IV2VNOK6FL22KUT/7QYRJOI3JIMYHGY6CH7SOIFRQLZOLNJ6/KFIAZD4RUMEZIYV6FQ3T3GP5PDBDB6JY.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramernEDMPIJV1",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "84.5",
                "framerIntrinsicHeight": "41",
                "framerComponentViewportWidth": "true",
                "framerContractVersion": "1",
                "framerVariables": "{\"ApxukoHYo\":\"title\",\"QkE8o0HIe\":\"link\",\"amWyVdppW\":\"newTab\"}",
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"AzhqezM_b\":{\"layout\":[\"auto\",\"auto\"]},\"MblpBuNJI\":{\"layout\":[\"auto\",\"auto\"]},\"Eq0ThAfha\":{\"layout\":[\"auto\",\"auto\"]},\"iKpejFiKn\":{\"layout\":[\"auto\",\"auto\"]},\"nvAn5gJ7R\":{\"layout\":[\"auto\",\"auto\"]}}}"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./nEDMPIJV1.map