// Generated by Framer (9e1dc8e)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {bodyClassName: "framer-body-wfGD9vxEt", breakpoints: [{hash: "1ecy690", mediaQuery: "(min-width: 1200px)"}, {hash: "tay2hy", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1oj51lc", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {BO3Ovis1d: "badge", eUBxFUTnZ: "badge-link", gx6iCen4n: "label", HbrGqWIwZ: "headings", j1LwHQSIv: "accordion", lN69wHuUj: "label-link", N_SjA6fyo: "button", nQs3SdcPs: "nav", s_NNiKr5c: "button-text", TbpfNyA35: "button-icon"}, robots: "max-image-preview:large", serializationId: "framer-ollRq", title: siteMetadata(params, activeLocale).title || "Styleguide", viewport: "width=device-width"}
}

export const metadataVersion = 1