// Generated by Framer (ce6e1ae)
import {
    LazyValue
} from "framer";
const valuesByLocaleId = {
    Ft06JUrhM: new LazyValue(() =>
        import ("./augiA20Il-0.js"))
};
export default function getLocalizedValue(key, locale) {
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const value = values.read()[key];
            if (value) return value;
        }
        locale = locale.fallback;
    }
}

function preload(locale) {
    const promises = [];
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const promise = values.preload();
            if (promise) promises.push(promise);
        }
        locale = locale.fallback;
    }
    if (promises.length > 0) return Promise.all(promises);
}
export function usePreloadLocalizedValues(locale) {
    const preloadPromise = preload(locale);
    if (preloadPromise) throw preloadPromise;
}
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "usePreloadLocalizedValues": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}