// Generated by Framer (9e1dc8e)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    cx,
    getLoadingLazyAtYPosition,
    Image,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
const serializationHash = "framer-B37TV";
const variantClassNames = {
    RTbTyDf3l: "framer-v-5tsxk7"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants === null || variants === void 0 ? void 0 : variants.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    bounce: .2,
    delay: 0,
    duration: .4,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value !== null && value !== void 0 ? value : config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    width,
    ...props
}) => {
    return { ...props
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "RTbTyDf3l",
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const ref1 = React.useRef(null);
    const defaultLayoutId = React.useId();
    const sharedStyleClassNames = [];
    const componentViewport = useComponentViewport();
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Image, { ...restProps,
                    ...gestureHandlers,
                    background: {
                        alt: "",
                        fit: "fill",
                        intrinsicHeight: 1100,
                        intrinsicWidth: 1920,
                        loading: getLoadingLazyAtYPosition((componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.y) || 0),
                        pixelHeight: 1100,
                        pixelWidth: 1920,
                        sizes: (componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw",
                        src: "https://framerusercontent.com/images/8G8Y8b1ZHwFvDzVUQQlr4waN1DI.jpg",
                        srcSet: "https://framerusercontent.com/images/8G8Y8b1ZHwFvDzVUQQlr4waN1DI.jpg?scale-down-to=512 512w,https://framerusercontent.com/images/8G8Y8b1ZHwFvDzVUQQlr4waN1DI.jpg?scale-down-to=1024 1024w,https://framerusercontent.com/images/8G8Y8b1ZHwFvDzVUQQlr4waN1DI.jpg 1920w"
                    },
                    className: cx(serializationHash, ...sharedStyleClassNames, "framer-5tsxk7", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "RTbTyDf3l",
                    ref: ref !== null && ref !== void 0 ? ref : ref1,
                    style: {
                        opacity: .08,
                        ...style
                    }
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-B37TV.framer-qx318g, .framer-B37TV .framer-qx318g { display: block; }", ".framer-B37TV.framer-5tsxk7 { height: 960px; overflow: hidden; position: relative; width: 1200px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 960
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerlXv0LgM3c = withCSS(Component, css, "framer-B37TV");
export default FramerlXv0LgM3c;
FramerlXv0LgM3c.displayName = "Layout/Body Background Image";
FramerlXv0LgM3c.defaultProps = {
    height: 960,
    width: 1200
};
addFonts(FramerlXv0LgM3c, [{
    explicitInter: true,
    fonts: []
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerlXv0LgM3c",
            "slots": [],
            "annotations": {
                "framerIntrinsicWidth": "1200",
                "framerContractVersion": "1",
                "framerImmutableVariables": "true",
                "framerDisplayContentsDiv": "false",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerComponentViewportWidth": "true",
                "framerIntrinsicHeight": "960"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./lXv0LgM3c.map