// Generated by Framer (ce6e1ae)
import {
    jsx as _jsx,
    jsxs as _jsxs,
    Fragment as _Fragment
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    Container,
    ControlType,
    cx,
    GeneratedComponentContext,
    getFonts,
    PropertyOverrides,
    RenderTarget,
    useActiveVariantCallback,
    useCustomCursors,
    useHydratedBreakpointVariants,
    useIsOnFramerCanvas,
    useLocaleInfo,
    useOverlayState,
    withCSS,
    withOptimizedAppearEffect
} from "framer";
import {
    AnimatePresence,
    LayoutGroup,
    motion
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import * as ReactDOM from "react-dom";
import Menu from "#framer/local/canvasComponent/ey9RMFL0A/ey9RMFL0A.js";
import LayoutBodyBackgroundImage from "#framer/local/canvasComponent/lXv0LgM3c/lXv0LgM3c.js";
import LayoutHeader from "#framer/local/canvasComponent/oGhHpErZD/oGhHpErZD.js";
import LayoutFooter from "#framer/local/canvasComponent/YQHzx1Vn8/YQHzx1Vn8.js";
const LayoutHeaderFonts = getFonts(LayoutHeader);
const MenuFonts = getFonts(Menu);
const LayoutFooterFonts = getFonts(LayoutFooter);
const ContainerWithOptimizedAppearEffect = withOptimizedAppearEffect(Container);
const LayoutBodyBackgroundImageFonts = getFonts(LayoutBodyBackgroundImage);
const breakpoints = {
    bjsAPPVHQ: "(min-width: 1200px)",
    kX65qxOg4: "(min-width: 810px) and (max-width: 1199px)",
    XTiylWl8M: "(max-width: 809px)"
};
const isBrowser = () => typeof document !== "undefined";
const serializationHash = "framer-IZukC";
const variantClassNames = {
    bjsAPPVHQ: "framer-v-zclkw6",
    kX65qxOg4: "framer-v-1r1q3e1",
    XTiylWl8M: "framer-v-1auuoho"
};
const transition1 = {
    bounce: .2,
    delay: .1,
    duration: .5,
    type: "spring"
};
const animation = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition1,
    x: 0,
    y: 0
};
const transition2 = {
    bounce: .2,
    delay: 0,
    duration: .5,
    type: "spring"
};
const animation1 = {
    opacity: 1,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transition: transition2,
    x: 0,
    y: 0
};
const animation2 = {
    opacity: 0,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    x: 0,
    y: 0
};
const getContainer = () => {
    return document.querySelector("#template-overlay") ? ? document.querySelector("#overlay") ? ? document.body;
};
const Overlay = ({
    children,
    blockDocumentScrolling,
    enabled = true
}) => {
    const [visible, setVisible] = useOverlayState({
        blockDocumentScrolling
    });
    return children({
        hide: () => setVisible(false),
        show: () => setVisible(true),
        toggle: () => setVisible(!visible),
        visible: enabled && visible
    });
};
const transition3 = {
    delay: 0,
    duration: .5,
    ease: [.5, 0, .88, .77],
    type: "tween"
};
const animation3 = {
    opacity: 1,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transformPerspective: 1200,
    transition: transition3,
    x: 0,
    y: 0
};
const animation4 = {
    opacity: .001,
    rotate: 0,
    rotateX: 0,
    rotateY: 0,
    scale: 1,
    skewX: 0,
    skewY: 0,
    transformPerspective: 1200,
    x: 0,
    y: 0
};
const breakpointRules = {
    kX65qxOg4: [".framer-IZukC.framer-zclkw6 { padding: 16px; }", ".framer-IZukC .framer-1yvaye5-container { left: 50%; top: 40px; transform: translateX(-50%); }"],
    XTiylWl8M: [".framer-IZukC.framer-zclkw6 { gap: 12px; padding: 12px; }", ".framer-IZukC .framer-1yvaye5-container { left: 50%; top: 24px; transform: translateX(-50%); }", '.framer-IZukC .framer-1q2yd07, [data-layout-template="true"] > #overlay { margin-bottom: -12px; }']
};
const breakpointKeys = Object.keys(breakpointRules);
const selectors = {
    kX65qxOg4: ".framer-1r1q3e1-override",
    XTiylWl8M: ".framer-1auuoho-override"
};
const rules = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-IZukC.framer-2or2yz, .framer-IZukC .framer-2or2yz { display: block; }", ".framer-IZukC.framer-zclkw6 { align-content: center; align-items: center; background-color: var(--token-4321a524-8651-4268-85f9-e884d8cb6223, #ffffff); display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 16px 0px 16px; position: relative; width: 100%; }", ".framer-IZukC .framer-1yvaye5-container { flex: none; height: auto; left: 72px; position: var(--framer-canvas-fixed-position, fixed); top: 72px; width: auto; z-index: 10; }", ".framer-IZukC.framer-k3je0g { background-color: var(--token-4321a524-8651-4268-85f9-e884d8cb6223, #0a0b0a); inset: 0px; position: fixed; user-select: none; z-index: 10; }", ".framer-IZukC.framer-1isoj6h-container { flex: none; height: 100%; left: 0px; position: fixed; top: 0px; width: 100%; will-change: var(--framer-will-change-effect-override, transform); z-index: 10; }", ".framer-IZukC .framer-1q2yd07 { background: transparent; flex-grow: 1; height: 0px; margin: 0px; margin-bottom: -16px; position: relative; width: 0px; }", ".framer-IZukC .framer-1lcp6bd-container { flex: none; height: auto; order: 1002; position: relative; width: 100%; will-change: var(--framer-will-change-effect-override, transform); }", ".framer-IZukC .framer-xyw2qg-container { flex: none; height: calc(min(var(--framer-viewport-height, 100vh), 100%) * 1); left: 0px; order: 1003; position: var(--framer-canvas-fixed-position, fixed); top: 0px; width: 100%; z-index: 1; }", '[data-layout-template="true"] > #overlay { margin-bottom: -16px; }'];
const mediaQueries = {
    bjsAPPVHQ: "(min-width: 1200px)",
    kX65qxOg4: "(min-width: 810px) and (max-width: 1199px)",
    XTiylWl8M: "(max-width: 809px)"
};
const HTMLStyle = ({
    value
}) => {
    const onCanvas = useIsOnFramerCanvas();
    if (onCanvas) return null;
    return /*#__PURE__*/ _jsx("style", {
        dangerouslySetInnerHTML: {
            __html: value
        },
        "data-framer-html-style": ""
    });
};
const humanReadableVariantMap = {
    Desktop: "bjsAPPVHQ",
    Phone: "XTiylWl8M",
    Tablet: "kX65qxOg4"
};
const getProps = ({
    height,
    id,
    showFooter,
    width,
    ...props
}) => {
    return { ...props,
        JyRc5iZM_: showFooter ? ? props.JyRc5iZM_ ? ? true,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "bjsAPPVHQ"
    };
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        JyRc5iZM_,
        children,
        ...restProps
    } = getProps(props);
    const [baseVariant, hydratedBaseVariant] = useHydratedBreakpointVariants(variant, breakpoints, false);
    const gestureVariant = undefined;
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(undefined);
    const OokibawIE3bnx0g = ({
        overlay,
        loadMore
    }) => activeVariantCallback(async (...args) => {
        overlay.toggle();
    });
    const woAUVjEwf1wnntms = ({
        overlay,
        loadMore
    }) => activeVariantCallback(async (...args) => {
        overlay.hide();
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const isDisplayed = value => {
        if (!isBrowser()) return true;
        if (["kX65qxOg4", "XTiylWl8M"].includes(baseVariant)) return value;
        return false;
    };
    useCustomCursors({});
    return /*#__PURE__*/ _jsx(GeneratedComponentContext.Provider, {
        value: {
            isLayoutTemplate: true,
            primaryVariantId: "bjsAPPVHQ",
            variantClassNames
        },
        children: /*#__PURE__*/ _jsxs(LayoutGroup, {
            id: layoutId ? ? defaultLayoutId,
            children: [ /*#__PURE__*/ _jsx(HTMLStyle, {
                value: ":root body { background: var(--token-4321a524-8651-4268-85f9-e884d8cb6223, rgb(255, 255, 255)); }"
            }), /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                className: cx(scopingClassNames, "framer-zclkw6", className),
                "data-layout-template": true,
                ref: refBinding,
                style: { ...style
                },
                children: [ /*#__PURE__*/ _jsx(Overlay, {
                    children: overlay => /*#__PURE__*/ _jsx(_Fragment, {
                        children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                            breakpoint: baseVariant,
                            overrides: {
                                kX65qxOg4: {
                                    y: 40
                                },
                                XTiylWl8M: {
                                    y: 24
                                }
                            },
                            children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 57,
                                y: 72,
                                children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                    breakpoint: baseVariant,
                                    overrides: {
                                        kX65qxOg4: {
                                            "data-framer-layout-hint-center-x": true
                                        },
                                        XTiylWl8M: {
                                            "data-framer-layout-hint-center-x": true
                                        }
                                    },
                                    children: /*#__PURE__*/ _jsxs(Container, {
                                        className: "framer-1yvaye5-container",
                                        layoutScroll: true,
                                        nodeId: "X5uwbANM2",
                                        scopeId: "yLpxGubdL",
                                        children: [ /*#__PURE__*/ _jsx(PropertyOverrides, {
                                            breakpoint: baseVariant,
                                            overrides: {
                                                XTiylWl8M: {
                                                    variant: "iYWmBinwv"
                                                }
                                            },
                                            children: /*#__PURE__*/ _jsx(LayoutHeader, {
                                                height: "100%",
                                                id: "X5uwbANM2",
                                                layoutId: "X5uwbANM2",
                                                OokibawIE: OokibawIE3bnx0g({
                                                    overlay
                                                }),
                                                variant: "sMX5M2Uqr",
                                                width: "100%"
                                            })
                                        }), /*#__PURE__*/ _jsx(AnimatePresence, {
                                            children: overlay.visible && /*#__PURE__*/ _jsx(_Fragment, {
                                                children: /*#__PURE__*/ ReactDOM.createPortal( /*#__PURE__*/ _jsxs(React.Fragment, {
                                                    children: [ /*#__PURE__*/ _jsx(motion.div, {
                                                        animate: {
                                                            opacity: 1
                                                        },
                                                        className: cx(scopingClassNames, "framer-k3je0g"),
                                                        exit: {
                                                            opacity: 0
                                                        },
                                                        initial: {
                                                            opacity: 0
                                                        },
                                                        onTap: () => overlay.hide(),
                                                        transition: {
                                                            delay: 0,
                                                            duration: 0,
                                                            ease: [.5, 0, .88, .77],
                                                            type: "tween"
                                                        }
                                                    }, "bBi1ZekB1"), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                                        width: "100vw",
                                                        children: /*#__PURE__*/ _jsx(Container, {
                                                            animate: animation1,
                                                            className: cx(scopingClassNames, "framer-1isoj6h-container"),
                                                            exit: animation,
                                                            inComponentSlot: true,
                                                            initial: animation2,
                                                            nodeId: "o4jOMc7R7",
                                                            rendersWithMotion: true,
                                                            scopeId: "yLpxGubdL",
                                                            children: /*#__PURE__*/ _jsx(Menu, {
                                                                height: "100%",
                                                                id: "o4jOMc7R7",
                                                                layoutId: "o4jOMc7R7",
                                                                style: {
                                                                    height: "100%",
                                                                    width: "100%"
                                                                },
                                                                variant: "EGqK4uSJI",
                                                                width: "100%",
                                                                woAUVjEwf: woAUVjEwf1wnntms({
                                                                    overlay
                                                                })
                                                            })
                                                        })
                                                    })]
                                                }), getContainer())
                                            })
                                        })]
                                    })
                                })
                            })
                        })
                    })
                }), children, /*#__PURE__*/ _jsx("div", {
                    className: "framer-1q2yd07"
                }), isDisplayed(JyRc5iZM_) && /*#__PURE__*/ _jsx(PropertyOverrides, {
                    breakpoint: baseVariant,
                    overrides: {
                        kX65qxOg4: {
                            height: 62,
                            width: "calc(100vw - 32px)",
                            y: 1016
                        },
                        XTiylWl8M: {
                            height: 62,
                            width: "calc(100vw - 24px)",
                            y: 1012
                        }
                    },
                    children: /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        children: /*#__PURE__*/ _jsx(ContainerWithOptimizedAppearEffect, {
                            animate: animation3,
                            className: cx("framer-1lcp6bd-container", "hidden-zclkw6", !JyRc5iZM_ && "hidden-1r1q3e1", !JyRc5iZM_ && "hidden-1auuoho"),
                            "data-framer-appear-id": "1lcp6bd",
                            initial: animation4,
                            nodeId: "tKGgNfGFD",
                            optimized: true,
                            rendersWithMotion: true,
                            scopeId: "yLpxGubdL",
                            style: {
                                transformPerspective: 1200
                            },
                            children: /*#__PURE__*/ _jsx(PropertyOverrides, {
                                breakpoint: baseVariant,
                                overrides: {
                                    XTiylWl8M: {
                                        variant: "JD6pMfzso"
                                    }
                                },
                                children: /*#__PURE__*/ _jsx(LayoutFooter, {
                                    height: "100%",
                                    id: "tKGgNfGFD",
                                    layoutId: "tKGgNfGFD",
                                    style: {
                                        width: "100%"
                                    },
                                    variant: "hEIfSvQFz",
                                    width: "100%"
                                })
                            })
                        })
                    })
                }), /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                    height: 1e3,
                    width: "100vw",
                    y: 0,
                    children: /*#__PURE__*/ _jsx(Container, {
                        className: "framer-xyw2qg-container",
                        layoutScroll: true,
                        nodeId: "r9m388FsC",
                        scopeId: "yLpxGubdL",
                        children: /*#__PURE__*/ _jsx(LayoutBodyBackgroundImage, {
                            height: "100%",
                            id: "r9m388FsC",
                            layoutId: "r9m388FsC",
                            style: {
                                height: "100%",
                                width: "100%"
                            },
                            width: "100%"
                        })
                    })
                })]
            }), /*#__PURE__*/ _jsx("div", {
                id: "template-overlay"
            })]
        })
    });
});
const css = target => {
    const isStaticRenderer = target === RenderTarget.canvas || target === RenderTarget.export;
    if (!isStaticRenderer) {
        return [...rules, ...breakpointKeys.map(key => {
            const query = mediaQueries[key];
            return `@media ${query} { ${breakpointRules[key].join(" ")} }`;
        })];
    }
    return [...rules, ...breakpointKeys.flatMap(key => {
        const selector = selectors[key];
        return breakpointRules[key].map(rule => `${selector} {${rule}}`);
    })];
};
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 1000
 * @framerIntrinsicWidth 1200
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","fixed"]},"kX65qxOg4":{"layout":["fixed","fixed"]},"XTiylWl8M":{"layout":["fixed","fixed"]}}}
 * @framerVariables {"JyRc5iZM_":"showFooter"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 * @framerHitTargets {"bjsAPPVHQ":[".framer-1yvaye5-container",".framer-xyw2qg-container"],"kX65qxOg4":[".framer-1yvaye5-container",".framer-1lcp6bd-container",".framer-xyw2qg-container"],"XTiylWl8M":[".framer-1yvaye5-container",".framer-1lcp6bd-container",".framer-xyw2qg-container"]}
 * @framerBreakpoints {"bjsAPPVHQ":{"min":1200,"canvasClassName":"framer-zclkw6-override","minHeight":1000,"viewportHeight":1000,"name":"Desktop","width":1200,"rootFontSize":16},"kX65qxOg4":{"min":810,"max":1199,"canvasClassName":"framer-1r1q3e1-override","minHeight":900,"viewportHeight":1000,"name":"Tablet","width":810,"rootFontSize":16},"XTiylWl8M":{"max":809,"canvasClassName":"framer-1auuoho-override","minHeight":800,"viewportHeight":800,"name":"Phone","width":390,"rootFontSize":16}}
 * @framerDefaultVariant bjsAPPVHQ
 * @framerLayoutTemplate
 */
const FrameryLpxGubdL = withCSS(Component, css, "framer-IZukC");
export default FrameryLpxGubdL;
FrameryLpxGubdL.displayName = "Default";
FrameryLpxGubdL.defaultProps = {
    height: 1e3,
    width: 1200
};
addPropertyControls(FrameryLpxGubdL, {
    JyRc5iZM_: {
        defaultValue: true,
        title: "Show Footer",
        type: ControlType.Boolean
    }
});
addFonts(FrameryLpxGubdL, [{
    explicitInter: true,
    fonts: []
}, ...LayoutHeaderFonts, ...MenuFonts, ...LayoutFooterFonts, ...LayoutBodyBackgroundImageFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "default": {
            "type": "reactComponent",
            "name": "FrameryLpxGubdL",
            "slots": [],
            "annotations": {
                "framerDisplayContentsDiv": "false",
                "framerIntrinsicHeight": "1000",
                "framerVariables": "{\"JyRc5iZM_\":\"showFooter\"}",
                "framerColorSyntax": "true",
                "framerDefaultVariant": "bjsAPPVHQ",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"fixed\",\"fixed\"]},\"kX65qxOg4\":{\"layout\":[\"fixed\",\"fixed\"]},\"XTiylWl8M\":{\"layout\":[\"fixed\",\"fixed\"]}}}",
                "framerContractVersion": "1",
                "framerComponentViewportWidth": "true",
                "framerHitTargets": "{\"bjsAPPVHQ\":[\".framer-1yvaye5-container\",\".framer-xyw2qg-container\"],\"kX65qxOg4\":[\".framer-1yvaye5-container\",\".framer-1lcp6bd-container\",\".framer-xyw2qg-container\"],\"XTiylWl8M\":[\".framer-1yvaye5-container\",\".framer-1lcp6bd-container\",\".framer-xyw2qg-container\"]}",
                "framerBreakpoints": "{\"bjsAPPVHQ\":{\"min\":1200,\"canvasClassName\":\"framer-zclkw6-override\",\"minHeight\":1000,\"viewportHeight\":1000,\"name\":\"Desktop\",\"width\":1200,\"rootFontSize\":16},\"kX65qxOg4\":{\"min\":810,\"max\":1199,\"canvasClassName\":\"framer-1r1q3e1-override\",\"minHeight\":900,\"viewportHeight\":1000,\"name\":\"Tablet\",\"width\":810,\"rootFontSize\":16},\"XTiylWl8M\":{\"max\":809,\"canvasClassName\":\"framer-1auuoho-override\",\"minHeight\":800,\"viewportHeight\":800,\"name\":\"Phone\",\"width\":390,\"rootFontSize\":16}}",
                "framerAutoSizeImages": "true",
                "framerLayoutTemplate": "",
                "framerIntrinsicWidth": "1200",
                "framerImmutableVariables": "true"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}