// Generated by Framer (5b26096)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "kf2hor", mediaQuery: "(min-width: 1200px)"}, {hash: "19zcxg3", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1717dh4", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, framerSearch: {index: true}, robots: "max-image-preview:large", serializationId: "framer-t4Qtr", title: siteMetadata(params, activeLocale).title || "Blog Detail", viewport: "width=device-width"}
}

export const metadataVersion = 1