// Generated by Framer (5b26096)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1yok14j", mediaQuery: "(min-width: 1200px)"}, {hash: "1uog2qu", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "azw0gc", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-0zIeN", title: siteMetadata(params, activeLocale).title || "404", viewport: "width=device-width"}
}

export const metadataVersion = 1