// Generated by Framer (cf240c2)
import {
    jsx as _jsx
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ControlType,
    cx,
    Link,
    RichText,
    useComponentViewport,
    useLocaleInfo,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
const enabledGestures = {
    "I2847:4028;2843:3487": {
        hover: true
    }
};
const serializationHash = "framer-28Mcz";
const variantClassNames = {
    "I2847:4028;2843:3487": "framer-v-136wxrw"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants === null || variants === void 0 ? void 0 : variants.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value !== null && value !== void 0 ? value : config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const getProps = ({
    height,
    id,
    link,
    title,
    width,
    ...props
}) => {
    var _ref;
    return { ...props,
        i0H2fEiAL: (_ref = title !== null && title !== void 0 ? title : props.i0H2fEiAL) !== null && _ref !== void 0 ? _ref : "Menu",
        zELeGxU0d: link !== null && link !== void 0 ? link : props.zELeGxU0d
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const {
        style,
        className,
        layoutId,
        variant,
        zELeGxU0d,
        i0H2fEiAL,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        defaultVariant: "I2847:4028;2843:3487",
        enabledGestures,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const ref1 = React.useRef(null);
    const defaultLayoutId = React.useId();
    const sharedStyleClassNames = [];
    const componentViewport = useComponentViewport();
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsx(Link, {
                    href: zELeGxU0d,
                    children: /*#__PURE__*/ _jsx(motion.a, { ...restProps,
                        ...gestureHandlers,
                        className: `${cx(serializationHash,...sharedStyleClassNames,"framer-136wxrw",className,classNames)} framer-1s4epyd`,
                        "data-border": true,
                        "data-framer-name": "Variant 1",
                        layoutDependency: layoutDependency,
                        layoutId: "I2847:4028;2843:3487",
                        ref: ref !== null && ref !== void 0 ? ref : ref1,
                        style: {
                            "--border-bottom-width": "1px",
                            "--border-color": "rgba(51, 51, 48, 0)",
                            "--border-left-width": "1px",
                            "--border-right-width": "1px",
                            "--border-style": "solid",
                            "--border-top-width": "1px",
                            backgroundColor: "rgba(0, 0, 0, 0)",
                            borderBottomLeftRadius: 8,
                            borderBottomRightRadius: 8,
                            borderTopLeftRadius: 8,
                            borderTopRightRadius: 8,
                            ...style
                        },
                        variants: {
                            "I2847:4028;2843:3487-hover": {
                                "--border-color": "var(--token-68c05b50-ca7b-4173-82aa-ed42aea1a9b4, rgb(51, 51, 48))",
                                backgroundColor: "var(--token-cd2934a7-4e35-4347-a32c-9650fca4db23, rgba(24, 24, 24, 0.5))"
                            }
                        },
                        ...addPropertyOverrides({
                            "I2847:4028;2843:3487-hover": {
                                "data-framer-name": undefined
                            }
                        }, baseVariant, gestureVariant),
                        children: /*#__PURE__*/ _jsx(RichText, {
                            __fromCanvasComponent: true,
                            children: /*#__PURE__*/ _jsx(React.Fragment, {
                                children: /*#__PURE__*/ _jsx(motion.p, {
                                    style: {
                                        "--font-selector": "RlM7U2F0b3NoaS1yZWd1bGFy",
                                        "--framer-font-family": '"Satoshi", "Satoshi Placeholder", sans-serif',
                                        "--framer-font-size": "12px",
                                        "--framer-letter-spacing": "1px",
                                        "--framer-line-height": "130%",
                                        "--framer-text-color": "var(--extracted-r6o4lv, var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, rgb(239, 231, 210)))",
                                        "--framer-text-transform": "uppercase"
                                    },
                                    children: "Menu"
                                })
                            }),
                            className: "framer-uml6xa",
                            "data-framer-name": "Menu",
                            fonts: ["FS;Satoshi-regular"],
                            layoutDependency: layoutDependency,
                            layoutId: "I2847:4028;2843:3488",
                            style: {
                                "--extracted-r6o4lv": "var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, rgb(239, 231, 210))"
                            },
                            text: i0H2fEiAL,
                            verticalAlignment: "top",
                            withExternalLayout: true
                        })
                    })
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-28Mcz.framer-1s4epyd, .framer-28Mcz .framer-1s4epyd { display: block; }", ".framer-28Mcz.framer-136wxrw { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 12px; position: relative; text-decoration: none; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-28Mcz .framer-uml6xa { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", "@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-28Mcz.framer-136wxrw { gap: 0px; } .framer-28Mcz.framer-136wxrw > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-28Mcz.framer-136wxrw > :first-child { margin-left: 0px; } .framer-28Mcz.framer-136wxrw > :last-child { margin-right: 0px; } }", '.framer-28Mcz[data-border="true"]::after, .framer-28Mcz [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }'];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 39.5
 * @framerIntrinsicWidth 62
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"G_zL25FV3":{"layout":["auto","auto"]}}}
 * @framerVariables {"zELeGxU0d":"link","i0H2fEiAL":"title"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerComponentViewportWidth true
 */
const FramerP2xHZtHFC = withCSS(Component, css, "framer-28Mcz");
export default FramerP2xHZtHFC;
FramerP2xHZtHFC.displayName = "Components/Navbar Item";
FramerP2xHZtHFC.defaultProps = {
    height: 39.5,
    width: 62
};
addPropertyControls(FramerP2xHZtHFC, {
    zELeGxU0d: {
        title: "Link",
        type: ControlType.Link
    },
    i0H2fEiAL: {
        defaultValue: "Menu",
        displayTextArea: false,
        title: "Title",
        type: ControlType.String
    }
});
addFonts(FramerP2xHZtHFC, [{
    explicitInter: true,
    fonts: [{
        family: "Satoshi",
        source: "fontshare",
        style: "normal",
        url: "https://framerusercontent.com/third-party-assets/fontshare/wf/TTX2Z3BF3P6Y5BQT3IV2VNOK6FL22KUT/7QYRJOI3JIMYHGY6CH7SOIFRQLZOLNJ6/KFIAZD4RUMEZIYV6FQ3T3GP5PDBDB6JY.woff2",
        weight: "400"
    }]
}], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FramerP2xHZtHFC",
            "slots": [],
            "annotations": {
                "framerContractVersion": "1",
                "framerIntrinsicHeight": "39.5",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"G_zL25FV3\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerComponentViewportWidth": "true",
                "framerVariables": "{\"zELeGxU0d\":\"link\",\"i0H2fEiAL\":\"title\"}",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "62",
                "framerDisplayContentsDiv": "false"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}
//# sourceMappingURL=./P2xHZtHFC.map