// Generated by Framer (5b26096)

import siteMetadata from "../siteMetadata/siteMetadata";

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1k9t1q", mediaQuery: "(min-width: 1200px)"}, {hash: "5ljf2f", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "xd5ijx", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-NvWqP", title: siteMetadata(params, activeLocale).title || "Licensing", viewport: "width=device-width"}
}

export const metadataVersion = 1