// Generated by Framer (ce6e1ae)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1td9vov", mediaQuery: "(min-width: 1400px)"}, {hash: "g1i4v9", mediaQuery: "(min-width: 810px) and (max-width: 1399px)"}, {hash: "okrmbe", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {Hhkwd75jM: "urmaki", lDOg3SbvG: "special", o4gBkUJE6: "maki"}, robots: "max-image-preview:large", serializationId: "framer-TXHqh", title: siteMetadata(params, activeLocale).title || "Menu", viewport: "width=device-width"}
}

export const metadataVersion = 1