// Generated by Framer (cf240c2)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-aZrau .framer-styles-preset-105xi8i:not(.rich-text-wrapper), .framer-aZrau .framer-styles-preset-105xi8i.rich-text-wrapper a { --framer-link-current-text-color: var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, #efedfd); --framer-link-current-text-decoration: underline; --framer-link-hover-text-color: var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, #efedfd); --framer-link-hover-text-decoration: underline; --framer-link-text-color: var(--token-797a2fb4-2d14-46eb-9fb6-f38c1a9a545e, rgba(245, 242, 234, 0.7)); --framer-link-text-decoration: none; }"];
export const className = "framer-aZrau";
export const __FramerMetadata__ = {
    "exports": {
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}