// Generated by Framer (cf240c2)
import {
    fontStore
} from "framer";
fontStore.loadFonts([]);
export const fonts = [{
    explicitInter: true,
    fonts: []
}];
export const css = [".framer-Ov6PI .framer-styles-preset-d12qnh:not(.rich-text-wrapper), .framer-Ov6PI .framer-styles-preset-d12qnh.rich-text-wrapper a { --framer-link-current-text-color: var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, #efe7d2); --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-ba35ffdc-68bb-41bc-880c-4aa29d4488ec, #cfbe91); --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-c5c4fdcb-9482-48bb-aedf-353188472aae, #efe7d2); --framer-link-text-decoration: none; transition: color 0.3s cubic-bezier(0.5, 0, 0.88, 0.77) 0s; }"];
export const className = "framer-Ov6PI";
export const __FramerMetadata__ = {
    "exports": {
        "fonts": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "className": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "css": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}