// Generated by Framer (ce6e1ae)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "1u9ttqs", mediaQuery: "(min-width: 1200px)"}, {hash: "1yg57i0", mediaQuery: "(min-width: 810px) and (max-width: 1199px)"}, {hash: "1oxn73b", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {q2liDXL_s: "special"}, robots: "max-image-preview:large", serializationId: "framer-LZSWB", title: siteMetadata(params, activeLocale).title || "Reservation", viewport: "width=device-width"}
}

export const metadataVersion = 1