// Generated by Framer (ce6e1ae)

import siteMetadata from "../siteMetadata/siteMetadata";

const valuesByLocaleId = {}

function getLocalizedValue (key, locale){while (locale) {const values = valuesByLocaleId[locale.id]
if (values) {const value = values[key]
if (value) return value}
locale = locale.fallback}}

export default function metadata(params, activeLocale) {
return {breakpoints: [{hash: "7t6ujr", mediaQuery: "(min-width: 1400px)"}, {hash: "xaannk", mediaQuery: "(min-width: 810px) and (max-width: 1399px)"}, {hash: "ahefhj", mediaQuery: "(max-width: 809px)"}], description: siteMetadata(params, activeLocale).description, elements: {}, robots: "max-image-preview:large", serializationId: "framer-tZykp", title: siteMetadata(params, activeLocale).title || "Blog", viewport: "width=device-width"}
}

export const metadataVersion = 1