// Generated by Framer (ba156f5)
import {
    jsx as _jsx,
    jsxs as _jsxs
} from "react/jsx-runtime";
import {
    addFonts,
    addPropertyControls,
    ComponentViewportProvider,
    ControlType,
    cx,
    getFonts,
    ResolveLinks,
    SmartComponentScopedContainer,
    useActiveVariantCallback,
    useComponentViewport,
    useLocaleInfo,
    useRouter,
    useVariantState,
    withCSS
} from "framer";
import {
    LayoutGroup,
    motion,
    MotionConfigContext
} from "framer-motion";
import * as React from "react";
import {
    useRef
} from "react";
import getLocalizedValue from "https://framerusercontent.com/modules/uZGciBpGMqpheLTAkZrb/ntJ5zAipS02pnz4Z3YTv/oGhHpErZD.js";
import LayoutLogo from "https://framerusercontent.com/modules/qFHpcqiGDVJpC7UJgY2N/3IsO41BO68QF7j0hUhZn/LTYLc1ufz.js";
import ComponentsButton from "https://framerusercontent.com/modules/yaeIbOvRilu2IKMgztx8/l1F11INhdssXdIsgwnso/nEDMPIJV1.js";
import ComponentsNavbarItem from "https://framerusercontent.com/modules/pfTgrw7HxyOLBAdueq97/b3grXQRbSgjUC0HhzZji/P2xHZtHFC.js";
import MenuMenuNavToggle from "https://framerusercontent.com/modules/7YweVdEvuDW1N4UgNdJF/OK0yRHKtZIOu0w1h2nXy/sMGy05NeU.js";
const MenuMenuNavToggleFonts = getFonts(MenuMenuNavToggle);
const LayoutLogoFonts = getFonts(LayoutLogo);
const ComponentsNavbarItemFonts = getFonts(ComponentsNavbarItem);
const ComponentsButtonFonts = getFonts(ComponentsButton);
const cycleOrder = ["sMX5M2Uqr", "iYWmBinwv"];
const serializationHash = "framer-KxeEd";
const variantClassNames = {
    iYWmBinwv: "framer-v-1ja1fot",
    sMX5M2Uqr: "framer-v-x917yn"
};

function addPropertyOverrides(overrides, ...variants) {
    const nextOverrides = {};
    variants ? .forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]));
    return nextOverrides;
}
const transition1 = {
    damping: 60,
    delay: 0,
    mass: 1,
    stiffness: 500,
    type: "spring"
};
const Transition = ({
    value,
    children
}) => {
    const config = React.useContext(MotionConfigContext);
    const transition = value ? ? config.transition;
    const contextValue = React.useMemo(() => ({ ...config,
        transition
    }), [JSON.stringify(transition)]);
    return /*#__PURE__*/ _jsx(MotionConfigContext.Provider, {
        value: contextValue,
        children: children
    });
};
const Variants = motion.create(React.Fragment);
const humanReadableVariantMap = {
    Desktop: "sMX5M2Uqr",
    Phone: "iYWmBinwv"
};
const getProps = ({
    height,
    id,
    menuToggle,
    width,
    ...props
}) => {
    return { ...props,
        OokibawIE: menuToggle ? ? props.OokibawIE,
        variant: humanReadableVariantMap[props.variant] ? ? props.variant ? ? "sMX5M2Uqr"
    };
};
const createLayoutDependency = (props, variants) => {
    if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
    return variants.join("-");
};
const Component = /*#__PURE__*/ React.forwardRef(function(props, ref) {
    const fallbackRef = useRef(null);
    const refBinding = ref ? ? fallbackRef;
    const defaultLayoutId = React.useId();
    const {
        activeLocale,
        setLocale
    } = useLocaleInfo();
    const componentViewport = useComponentViewport();
    const {
        style,
        className,
        layoutId,
        variant,
        OokibawIE,
        ...restProps
    } = getProps(props);
    const {
        baseVariant,
        classNames,
        clearLoadingGesture,
        gestureHandlers,
        gestureVariant,
        isLoading,
        setGestureState,
        setVariant,
        variants
    } = useVariantState({
        cycleOrder,
        defaultVariant: "sMX5M2Uqr",
        ref: refBinding,
        variant,
        variantClassNames
    });
    const layoutDependency = createLayoutDependency(props, variants);
    const {
        activeVariantCallback,
        delay
    } = useActiveVariantCallback(baseVariant);
    const MKKuqG1x5lc2vqn = activeVariantCallback(async (...args) => {
        if (OokibawIE) {
            const res = await OokibawIE(...args);
            if (res === false) return false;
        }
    });
    const sharedStyleClassNames = [];
    const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
    const router = useRouter();
    const isDisplayed = () => {
        if (baseVariant === "iYWmBinwv") return false;
        return true;
    };
    return /*#__PURE__*/ _jsx(LayoutGroup, {
        id: layoutId ? ? defaultLayoutId,
        children: /*#__PURE__*/ _jsx(Variants, {
            animate: variants,
            initial: false,
            children: /*#__PURE__*/ _jsx(Transition, {
                value: transition1,
                children: /*#__PURE__*/ _jsxs(motion.div, { ...restProps,
                    ...gestureHandlers,
                    className: cx(scopingClassNames, "framer-x917yn", className, classNames),
                    "data-framer-name": "Desktop",
                    layoutDependency: layoutDependency,
                    layoutId: "sMX5M2Uqr",
                    ref: refBinding,
                    style: {
                        backgroundColor: "rgb(10, 11, 10)",
                        borderBottomLeftRadius: 12,
                        borderBottomRightRadius: 12,
                        borderTopLeftRadius: 12,
                        borderTopRightRadius: 12,
                        ...style
                    },
                    ...addPropertyOverrides({
                        iYWmBinwv: {
                            "data-framer-name": "Phone"
                        }
                    }, baseVariant, gestureVariant),
                    children: [ /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                        height: 41,
                        width: "41px",
                        y: (componentViewport ? .y || 0) + (8 + ((componentViewport ? .height || 57) - 16 - 41) / 2),
                        children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                            className: "framer-1xr4r8t-container",
                            layoutDependency: layoutDependency,
                            layoutId: "zKNLyiq_0-container",
                            nodeId: "zKNLyiq_0",
                            rendersWithMotion: true,
                            scopeId: "oGhHpErZD",
                            children: /*#__PURE__*/ _jsx(MenuMenuNavToggle, {
                                height: "100%",
                                id: "zKNLyiq_0",
                                layoutId: "zKNLyiq_0",
                                MKKuqG1x5: MKKuqG1x5lc2vqn,
                                style: {
                                    height: "100%",
                                    width: "100%"
                                },
                                width: "100%"
                            })
                        })
                    }), /*#__PURE__*/ _jsx(ResolveLinks, {
                        links: [{
                            href: {
                                webPageId: "augiA20Il"
                            },
                            implicitPathVariables: undefined
                        }, {
                            href: {
                                webPageId: "augiA20Il"
                            },
                            implicitPathVariables: undefined
                        }],
                        children: resolvedLinks => /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                            height: 30,
                            y: (componentViewport ? .y || 0) + (8 + ((componentViewport ? .height || 57) - 16 - 30) / 2),
                            ...addPropertyOverrides({
                                iYWmBinwv: {
                                    width: "90px"
                                }
                            }, baseVariant, gestureVariant),
                            children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                className: "framer-1un38sm-container",
                                layoutDependency: layoutDependency,
                                layoutId: "SMpgKPRwU-container",
                                nodeId: "SMpgKPRwU",
                                rendersWithMotion: true,
                                scopeId: "oGhHpErZD",
                                children: /*#__PURE__*/ _jsx(LayoutLogo, {
                                    a28gi3Ahz: resolvedLinks[0],
                                    height: "100%",
                                    id: "SMpgKPRwU",
                                    layoutId: "SMpgKPRwU",
                                    width: "100%",
                                    ...addPropertyOverrides({
                                        iYWmBinwv: {
                                            a28gi3Ahz: resolvedLinks[1],
                                            style: {
                                                width: "100%"
                                            }
                                        }
                                    }, baseVariant, gestureVariant)
                                })
                            })
                        })
                    }), /*#__PURE__*/ _jsxs(motion.div, {
                        className: "framer-uw18uo",
                        "data-framer-name": "Menu",
                        layoutDependency: layoutDependency,
                        layoutId: "I2847:4028;2843:3484",
                        children: [isDisplayed() && /*#__PURE__*/ _jsx(ResolveLinks, {
                            links: [{
                                href: {
                                    webPageId: "W61OseJy9"
                                },
                                implicitPathVariables: undefined
                            }],
                            children: resolvedLinks1 => /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 39,
                                y: (componentViewport ? .y || 0) + (8 + ((componentViewport ? .height || 57) - 16 - 41) / 2) + 1,
                                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                    className: "framer-1e6q382-container",
                                    layoutDependency: layoutDependency,
                                    layoutId: "iKkIWZoJ0-container",
                                    nodeId: "iKkIWZoJ0",
                                    rendersWithMotion: true,
                                    scopeId: "oGhHpErZD",
                                    children: /*#__PURE__*/ _jsx(ComponentsNavbarItem, {
                                        height: "100%",
                                        i0H2fEiAL: getLocalizedValue("v0", activeLocale) ? ? "Menu",
                                        id: "iKkIWZoJ0",
                                        layoutId: "iKkIWZoJ0",
                                        width: "100%",
                                        zELeGxU0d: resolvedLinks1[0]
                                    })
                                })
                            })
                        }), isDisplayed() && /*#__PURE__*/ _jsx(ResolveLinks, {
                            links: [{
                                href: {
                                    webPageId: "OFVwkEg7d"
                                },
                                implicitPathVariables: undefined
                            }],
                            children: resolvedLinks2 => /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 39,
                                y: (componentViewport ? .y || 0) + (8 + ((componentViewport ? .height || 57) - 16 - 41) / 2) + 1,
                                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                    className: "framer-1rkkrfi-container",
                                    layoutDependency: layoutDependency,
                                    layoutId: "HCB8r5_0f-container",
                                    nodeId: "HCB8r5_0f",
                                    rendersWithMotion: true,
                                    scopeId: "oGhHpErZD",
                                    children: /*#__PURE__*/ _jsx(ComponentsNavbarItem, {
                                        height: "100%",
                                        i0H2fEiAL: getLocalizedValue("v1", activeLocale) ? ? "About",
                                        id: "HCB8r5_0f",
                                        layoutId: "HCB8r5_0f",
                                        width: "100%",
                                        zELeGxU0d: resolvedLinks2[0]
                                    })
                                })
                            })
                        }), /*#__PURE__*/ _jsx(ResolveLinks, {
                            links: [{
                                href: {
                                    webPageId: "YCbNyRkzE"
                                },
                                implicitPathVariables: undefined
                            }, {
                                href: {
                                    webPageId: "YCbNyRkzE"
                                },
                                implicitPathVariables: undefined
                            }],
                            children: resolvedLinks3 => /*#__PURE__*/ _jsx(ComponentViewportProvider, {
                                height: 41,
                                y: (componentViewport ? .y || 0) + (8 + ((componentViewport ? .height || 57) - 16 - 41) / 2) + 0,
                                children: /*#__PURE__*/ _jsx(SmartComponentScopedContainer, {
                                    className: "framer-1h58hyq-container",
                                    layoutDependency: layoutDependency,
                                    layoutId: "JbkncrvJZ-container",
                                    nodeId: "JbkncrvJZ",
                                    rendersWithMotion: true,
                                    scopeId: "oGhHpErZD",
                                    children: /*#__PURE__*/ _jsx(ComponentsButton, {
                                        amWyVdppW: false,
                                        ApxukoHYo: getLocalizedValue("v2", activeLocale) ? ? "Book a Table",
                                        height: "100%",
                                        id: "JbkncrvJZ",
                                        layoutId: "JbkncrvJZ",
                                        QkE8o0HIe: resolvedLinks3[0],
                                        variant: "AzhqezM_b",
                                        width: "100%",
                                        ...addPropertyOverrides({
                                            iYWmBinwv: {
                                                QkE8o0HIe: resolvedLinks3[1]
                                            }
                                        }, baseVariant, gestureVariant)
                                    })
                                })
                            })
                        })]
                    })]
                })
            })
        })
    });
});
const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-KxeEd.framer-16hkge3, .framer-KxeEd .framer-16hkge3 { display: block; }", ".framer-KxeEd.framer-x917yn { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 8px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }", ".framer-KxeEd .framer-1xr4r8t-container { flex: none; height: 41px; position: relative; width: 41px; }", ".framer-KxeEd .framer-1un38sm-container, .framer-KxeEd .framer-1e6q382-container, .framer-KxeEd .framer-1rkkrfi-container, .framer-KxeEd .framer-1h58hyq-container { flex: none; height: auto; position: relative; width: auto; }", ".framer-KxeEd .framer-uw18uo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-KxeEd.framer-v-1ja1fot .framer-1un38sm-container { width: 90px; }"];
/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 57
 * @framerIntrinsicWidth 445
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["auto","auto"]},"iYWmBinwv":{"layout":["auto","auto"]}}}
 * @framerVariables {"OokibawIE":"menuToggle"}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FrameroGhHpErZD = withCSS(Component, css, "framer-KxeEd");
export default FrameroGhHpErZD;
FrameroGhHpErZD.displayName = "Layout/Header";
FrameroGhHpErZD.defaultProps = {
    height: 57,
    width: 445
};
addPropertyControls(FrameroGhHpErZD, {
    variant: {
        options: ["sMX5M2Uqr", "iYWmBinwv"],
        optionTitles: ["Desktop", "Phone"],
        title: "Variant",
        type: ControlType.Enum
    },
    OokibawIE: {
        title: "Menu Toggle",
        type: ControlType.EventHandler
    }
});
addFonts(FrameroGhHpErZD, [{
    explicitInter: true,
    fonts: []
}, ...MenuMenuNavToggleFonts, ...LayoutLogoFonts, ...ComponentsNavbarItemFonts, ...ComponentsButtonFonts], {
    supportsExplicitInterCodegen: true
});
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "reactComponent",
            "name": "FrameroGhHpErZD",
            "slots": [],
            "annotations": {
                "framerAutoSizeImages": "true",
                "framerColorSyntax": "true",
                "framerIntrinsicHeight": "57",
                "framerVariables": "{\"OokibawIE\":\"menuToggle\"}",
                "framerDisplayContentsDiv": "false",
                "framerContractVersion": "1",
                "framerCanvasComponentVariantDetails": "{\"propertyName\":\"variant\",\"data\":{\"default\":{\"layout\":[\"auto\",\"auto\"]},\"iYWmBinwv\":{\"layout\":[\"auto\",\"auto\"]}}}",
                "framerImmutableVariables": "true",
                "framerIntrinsicWidth": "445",
                "framerComponentViewportWidth": "true"
            }
        },
        "Props": {
            "type": "tsType",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}