// Generated by Framer (ce6e1ae)

import { addFonts, addPropertyControls, ControlType, cx, getFontsFromSharedStyle, Link, RichText, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "framer";
import { LayoutGroup, motion, MotionConfigContext } from "framer-motion";
import * as React from "react";
import { useRef } from "react";
import * as sharedStyle1 from "../css/EV67tfIBO";
import * as sharedStyle from "../css/NWkCScbQS";

const cycleOrder = ["hEIfSvQFz", "JD6pMfzso"];

const serializationHash = "framer-JuOmG"

const variantClassNames = {hEIfSvQFz: "framer-v-aqkljq", JD6pMfzso: "framer-v-1620m3r"};

function addPropertyOverrides(overrides, ...variants) {
const nextOverrides = {}
variants?.forEach(variant => variant && Object.assign(nextOverrides, overrides[variant]))
return nextOverrides
}

const transition1 = {damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring"}

const Transition = ({value, children}) => {
const config = React.useContext(MotionConfigContext)
const transition = value ?? config.transition
const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)])
return <MotionConfigContext.Provider value={contextValue}>{children}</MotionConfigContext.Provider>
}

const Variants = motion.create(React.Fragment)

const humanReadableVariantMap = {Desktop: "hEIfSvQFz", Phone: "JD6pMfzso"}

const getProps = ({height, id, width, ...props}) => { return {...props, variant: humanReadableVariantMap[props.variant] ?? props.variant ?? "hEIfSvQFz"} }

const createLayoutDependency = (props, variants) => {if (props.layoutDependency) return variants.join('-') + props.layoutDependency
return variants.join('-')}

export interface Props extends React.HTMLAttributes<HTMLDivElement> { style?: Record<string, unknown>;className?: string;layoutId?: string | number;variant?: keyof typeof humanReadableVariantMap; }

const Component = React.forwardRef<HTMLDivElement, Props>(function(props, ref) {

const fallbackRef = useRef<HTMLElement>(null)

const refBinding = ref ?? fallbackRef

const defaultLayoutId = React.useId()

const { activeLocale, setLocale } = useLocaleInfo()

const componentViewport = useComponentViewport()

const { style, className, layoutId, variant, ...restProps } = getProps(props)

const {baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants} = useVariantState({cycleOrder, defaultVariant: "hEIfSvQFz", ref: refBinding, variant, variantClassNames})

const layoutDependency = createLayoutDependency(props, variants)

const sharedStyleClassNames = [sharedStyle.className, sharedStyle1.className]

const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames)

return (<LayoutGroup id={layoutId ?? defaultLayoutId}><Variants animate={variants} initial={false}><Transition value={transition1}><motion.div {...restProps} {...gestureHandlers} className={cx(scopingClassNames, "framer-aqkljq", className, classNames)} data-border data-framer-name={"Desktop"} layoutDependency={layoutDependency} layoutId={"hEIfSvQFz"} ref={refBinding} style={{"--border-bottom-width": "1px", "--border-color": "var(--token-68c05b50-ca7b-4173-82aa-ed42aea1a9b4, rgb(51, 51, 48))", "--border-left-width": "1px", "--border-right-width": "1px", "--border-style": "solid", "--border-top-width": "1px", borderBottomLeftRadius: 16, borderBottomRightRadius: 16, borderTopLeftRadius: 16, borderTopRightRadius: 16, ...style}} {...addPropertyOverrides({JD6pMfzso: {"data-framer-name": "Phone"}}, baseVariant, gestureVariant)}><motion.div className={"framer-1uul33g"} layoutDependency={layoutDependency} layoutId={"I2940:6841;2940:6837"}><RichText __fromCanvasComponent children={<React.Fragment><motion.p className={"framer-styles-preset-1cqwskc"} data-styles-preset={"NWkCScbQS"} style={{"--framer-text-color": "var(--extracted-r6o4lv, var(--token-797a2fb4-2d14-46eb-9fb6-f38c1a9a545e, rgba(245, 242, 234, 0.7)))"}}><Link href={"https://gola.supply"} motionChild nodeId={"I2940:6841;2940:6836"} openInNewTab relValues={[]} scopeId={"YQHzx1Vn8"} smoothScroll={false}><motion.a className={"framer-styles-preset-105xi8i"} data-styles-preset={"EV67tfIBO"}>© </motion.a></Link>CRAFTPARK media</motion.p></React.Fragment>} className={"framer-18gr9up"} fonts={["Inter"]} layoutDependency={layoutDependency} layoutId={"I2940:6841;2940:6836"} style={{"--extracted-r6o4lv": "var(--token-797a2fb4-2d14-46eb-9fb6-f38c1a9a545e, rgba(245, 242, 234, 0.7))"}} verticalAlignment={"top"} withExternalLayout/></motion.div></motion.div></Transition></Variants></LayoutGroup>)

});

const css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-JuOmG.framer-120osfk, .framer-JuOmG .framer-120osfk { display: block; }", ".framer-JuOmG.framer-aqkljq { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 80px; height: min-content; justify-content: center; overflow: visible; padding: 24px; position: relative; width: 668px; }", ".framer-JuOmG .framer-1uul33g { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }", ".framer-JuOmG .framer-18gr9up { flex: none; height: auto; position: relative; white-space: pre; width: auto; }", ".framer-JuOmG.framer-v-1620m3r.framer-aqkljq { flex-direction: column; gap: 12px; justify-content: flex-start; width: 390px; }", ".framer-JuOmG.framer-v-1620m3r .framer-1uul33g { flex-direction: column; order: 0; }", ".framer-JuOmG.framer-v-1620m3r .framer-18gr9up { order: 0; }", ...sharedStyle.css, ...sharedStyle1.css, ".framer-JuOmG[data-border=\"true\"]::after, .framer-JuOmG [data-border=\"true\"]::after { content: \"\"; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }"]

/**
 * This is a generated Framer component.
 * @framerIntrinsicHeight 62.5
 * @framerIntrinsicWidth 668
 * @framerCanvasComponentVariantDetails {"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"JD6pMfzso":{"layout":["fixed","auto"]}}}
 * @framerImmutableVariables true
 * @framerDisplayContentsDiv false
 * @framerAutoSizeImages true
 * @framerComponentViewportWidth true
 * @framerColorSyntax true
 */
const FramerYQHzx1Vn8: React.ComponentType<Props> = withCSS(Component, css, "framer-JuOmG") as typeof Component;
export default FramerYQHzx1Vn8;

FramerYQHzx1Vn8.displayName = "Layout/Footer";

FramerYQHzx1Vn8.defaultProps = {height: 62.5, width: 668};

addPropertyControls(FramerYQHzx1Vn8, {variant: {options: ["hEIfSvQFz", "JD6pMfzso"], optionTitles: ["Desktop", "Phone"], title: "Variant", type: ControlType.Enum}} as any)

addFonts(FramerYQHzx1Vn8, [{explicitInter: true, fonts: [{family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F", url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116", url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+1F00-1FFF", url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0370-03FF", url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF", url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD", url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2", weight: "400"}, {family: "Inter", source: "framer", style: "normal", unicodeRange: "U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB", url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2", weight: "400"}]}, ...getFontsFromSharedStyle(sharedStyle.fonts), ...getFontsFromSharedStyle(sharedStyle1.fonts)], {supportsExplicitInterCodegen: true})