// Generated by Framer (ce6e1ae)
const valuesByLocaleId = {
    Ft06JUrhM: {
        v0: "Qitchen - SUSHI Restaurace",
        v1: "Qitchen představuje sofistikovanou šablonu r\xe1mce restaurace, navrženou pro j\xeddeln\xed zař\xedzen\xed, restaurace, bary, kav\xe1rny, kav\xe1rensk\xe1 centra a podniky zab\xfdvaj\xedc\xed se potravinami nebo n\xe1poji."
    }
};

function getLocalizedValue(key, locale) {
    while (locale) {
        const values = valuesByLocaleId[locale.id];
        if (values) {
            const value = values[key];
            if (value) return value;
        }
        locale = locale.fallback;
    }
}
export default function metadata(params, activeLocale) {
    return {
        description: getLocalizedValue("v1", activeLocale) ? ? "Qitchen embodies a sophisticated Restaurant Framer Template, tailored for dining establishments, restaurants, bars, cafes, coffee hubs, and food or beverage businesses.",
        favicon: "https://framerusercontent.com/assets/SQZDQj2gDkUmN9upKjykPnd1NM.png",
        robots: "max-image-preview:large",
        socialImage: "https://framerusercontent.com/assets/xGiaa6XJMtLwGaER3ktbHa34.webp",
        title: getLocalizedValue("v0", activeLocale) ? ? "Qitchen - Restaurant Framer Template"
    };
}
export const metadataVersion = 1;
export const __FramerMetadata__ = {
    "exports": {
        "default": {
            "type": "function",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "metadataVersion": {
            "type": "variable",
            "annotations": {
                "framerContractVersion": "1"
            }
        },
        "__FramerMetadata__": {
            "type": "variable"
        }
    }
}